USE SCSCg1;
GO

CREATE TABLE CLIENT(
    CID INT PRIMARY KEY,
    CompanyName NVARCHAR(100) NOT NULL UNIQUE,
    ContactPerson NVARCHAR(100) NOT NULL,
    StartDate DATE NOT NULL,
    ServiceTier NVARCHAR(10) NOT NULL
        CHECK (ServiceTier IN ('Bronze', 'Silver', 'Gold', 'Platinum'))
);

CREATE TABLE SUPPLIER(
    SupplierID INT PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Country NVARCHAR(50) NOT NULL,
    PaymentTerms NVARCHAR(50) NOT NULL,
    LeadTime INT NOT NULL CHECK (LeadTime >= 0)
);

CREATE TABLE PRODUCT(
    PID INT PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Brand NVARCHAR(100) NOT NULL,
    Cost DECIMAL(10,2) NOT NULL CHECK (Cost > 0),
    Price DECIMAL(10,2) NOT NULL CHECK (Price > 0),
    Category NVARCHAR(50) NOT NULL,
    Length DECIMAL(10,2) NOT NULL CHECK (Length > 0),
    Width DECIMAL(10,2) NOT NULL CHECK (Width > 0),
    Height DECIMAL(10,2) NOT NULL CHECK (Height > 0),
    HandlingRequirements NVARCHAR(100) NULL,
    CHECK (Price >= Cost)
);

CREATE TABLE WAREHOUSE(
    WID INT PRIMARY KEY,
    Address NVARCHAR(100) NOT NULL UNIQUE,
    Size DECIMAL(10,2) NOT NULL CHECK (Size > 0),
    Temperature DECIMAL(5,2) NOT NULL,
    Security NVARCHAR(50) NOT NULL
        CHECK (Security IN ('Basic', 'Standard', 'High', 'Maximum'))
);

CREATE TABLE STAFF(
    StaffID INT PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    HireDate DATE NOT NULL DEFAULT GETDATE(),
    Type NVARCHAR(20) NOT NULL
        CHECK (Type IN ('Part time', 'Full time'))
);

CREATE TABLE VEHICLE(
    VID INT PRIMARY KEY,
    License NVARCHAR(20) NOT NULL UNIQUE,
    Type NVARCHAR(50) NOT NULL,
    Capacity DECIMAL(10,2) NOT NULL CHECK (Capacity > 0)
);

CREATE TABLE ROUTE(
    RID INT PRIMARY KEY,
    Date DATE NOT NULL,
    TotalDistance DECIMAL(10,2) NOT NULL CHECK (TotalDistance > 0),
    TotalStops INT NOT NULL CHECK (TotalStops >= 0),
    Status NVARCHAR(20) DEFAULT 'Planned'
        CHECK (Status IN ('Planned', 'In Progress', 'Completed', 'Cancelled'))
);

-- IMPORTANT: Create LICENSE_INFO before DRIVER
CREATE TABLE LICENSE_INFO(
    LicenseNumber NVARCHAR(20) PRIMARY KEY,
    LicenseExpiration DATE NOT NULL
);

CREATE TABLE EMPLOYEE(
    StaffID INT PRIMARY KEY REFERENCES STAFF(StaffID) ON DELETE CASCADE,
    Certification NVARCHAR(100) NOT NULL,
    WID INT NOT NULL REFERENCES WAREHOUSE(WID)
);

CREATE TABLE DRIVER(
    StaffID INT PRIMARY KEY REFERENCES STAFF(StaffID) ON DELETE CASCADE,
    LicenseNumber NVARCHAR(20) NOT NULL UNIQUE
        REFERENCES LICENSE_INFO(LicenseNumber),
    VID INT NOT NULL REFERENCES VEHICLE(VID)
);

CREATE TABLE ITEM(
    ItemSerialNo INT PRIMARY KEY,
    PID INT NOT NULL REFERENCES PRODUCT(PID)
);

CREATE TABLE PURCHASE_ORDER(
    OID INT PRIMARY KEY,
    OrderDate DATE NOT NULL DEFAULT GETDATE(),
    Status NVARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (Status IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')),
    Value DECIMAL(10,2) NOT NULL CHECK (Value > 0)
);

CREATE TABLE ORDER_ITEM(
    OID INT NOT NULL REFERENCES PURCHASE_ORDER(OID),
    ItemSerialNo INT NOT NULL REFERENCES ITEM(ItemSerialNo),
    OrderedQty INT NOT NULL CHECK (OrderedQty > 0),
    UnitPrice DECIMAL(10,2) NOT NULL CHECK (UnitPrice > 0),
    ExDelDate DATE NOT NULL,
    PRIMARY KEY (OID, ItemSerialNo)
);

CREATE TABLE SHIPMENT(
    ShipmentID INT PRIMARY KEY,
    OriginalLocation NVARCHAR(100) NOT NULL,
    TrackingNumber NVARCHAR(30) NOT NULL UNIQUE,
    ShippedDate DATE NOT NULL,
    ExArrDate DATE NOT NULL,
    AcArrDate DATE NULL,
    OID INT NOT NULL REFERENCES PURCHASE_ORDER(OID),
    CHECK (ShippedDate <= ExArrDate)
);

CREATE TABLE SHIP_ITEM(
    ShipmentID INT NOT NULL REFERENCES SHIPMENT(ShipmentID),
    ItemSerialNo INT NOT NULL REFERENCES ITEM(ItemSerialNo),
    ShippedQty INT NOT NULL CHECK (ShippedQty > 0),
    ExArrDate DATE NOT NULL,
    PRIMARY KEY (ShipmentID, ItemSerialNo)
);

CREATE TABLE ZONE(
    WID INT NOT NULL REFERENCES WAREHOUSE(WID) ON DELETE CASCADE,
    Code INT NOT NULL,
    PRIMARY KEY (WID, Code)
);

CREATE TABLE LOCATION(
    LocationID INT PRIMARY KEY,
    LocationName NVARCHAR(100) NOT NULL,
    WID INT NOT NULL,
    Code INT NOT NULL,
    FOREIGN KEY (WID, Code) REFERENCES ZONE(WID, Code) ON DELETE CASCADE
);

CREATE TABLE STOP(
    RID INT NOT NULL REFERENCES ROUTE(RID) ON DELETE CASCADE,
    Sequence INT NOT NULL,
    EstArrTime DATETIME NOT NULL,
    ActArrTime DATETIME NULL,
    PRIMARY KEY (RID, Sequence)
);

CREATE TABLE DELIVERY(
    RID INT NOT NULL REFERENCES ROUTE(RID),
    VID INT NOT NULL REFERENCES VEHICLE(VID),
    WID INT NOT NULL REFERENCES WAREHOUSE(WID),
    ShipmentID INT NOT NULL REFERENCES SHIPMENT(ShipmentID),
    DeliveryDate DATE NOT NULL,
    PRIMARY KEY (RID, VID, WID, ShipmentID, DeliveryDate)
);

CREATE TABLE CLIENT_PURCHASE_ORDER(
    OID INT NOT NULL REFERENCES PURCHASE_ORDER(OID),
    CID INT NOT NULL REFERENCES CLIENT(CID),
    PRIMARY KEY (OID, CID)
);

CREATE TABLE SUPPLIER_PURCHASE_ORDER(
    OID INT NOT NULL REFERENCES PURCHASE_ORDER(OID),
    SupplierID INT NOT NULL REFERENCES SUPPLIER(SupplierID),
    PRIMARY KEY (OID, SupplierID)
);

CREATE TABLE INVENTORY_MOVEMENT(
    Timestamp DATETIME PRIMARY KEY DEFAULT GETDATE(),
    Movement NVARCHAR(20) NOT NULL
        CHECK (Movement IN ('In', 'Out', 'Transfer', 'Other')),
    Reasons NVARCHAR(100) NOT NULL
);

CREATE TABLE INVENTORY(
    PID INT NOT NULL REFERENCES PRODUCT(PID),
    WID INT NOT NULL REFERENCES WAREHOUSE(WID),
    CID INT NOT NULL REFERENCES CLIENT(CID),
    SerialNo INT NOT NULL,
    rQty INT NOT NULL DEFAULT 0 CHECK (rQty >= 0),
    hQty INT NOT NULL DEFAULT 0 CHECK (hQty >= 0),
    sQty INT NOT NULL DEFAULT 0 CHECK (sQty >= 0),
    oQty INT NOT NULL DEFAULT 0 CHECK (oQty >= 0),
    Timestamp DATETIME NOT NULL
        REFERENCES INVENTORY_MOVEMENT(Timestamp),
    PRIMARY KEY (PID, WID, CID, SerialNo)
);

CREATE TABLE SUPPLY(
    CID INT NOT NULL REFERENCES CLIENT(CID),
    SupplierID INT NOT NULL REFERENCES SUPPLIER(SupplierID),
    PID INT NOT NULL REFERENCES PRODUCT(PID),
    Period INT NOT NULL CHECK (Period > 0),
    PRIMARY KEY (CID, SupplierID, PID)
);

CREATE TABLE SHIPMENT_TO_WAREHOUSE(
    ShipmentID INT NOT NULL REFERENCES SHIPMENT(ShipmentID),
    WID INT NOT NULL REFERENCES WAREHOUSE(WID),
    PRIMARY KEY (ShipmentID, WID)
);
